apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-laura-mejia
  namespace: namespace-laura-mejia
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 