apiVersion: v1
kind: Service
metadata:
  name: nodeport-laura-mejia
  namespace: namespace-laura-mejia
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007