apiVersion: v1
kind: Service
metadata:
  name: servicio-laura-mejia
  namespace: namespace-laura-mejia
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80